[tool.black]
line-length = 119
target-version = ["py312"]
exclude = '''
    /(
          \.git
        | \.github
        | \.vscode
        | \.venv
        | venv
        | \.devcontainer
        | data
        | models
        | prompts
        | docs
    )/
'''
