[tool.black]
line-length = 119
target-version = ["py312"]
exclude = '''
    /(
          \.git
        | \.github
        | \.vscode
        | \.venv
        | venv
        | \.devcontainer
        | data
        | models
        | prompts
        | docs
    )/
'''

[tool.djlint]
profile = "jinja"

[tool.isort]
profile = "black"
