name: Lint and Format Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-format-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check import sorting with iSort
        uses: isort/isort-action@master

      - name: Check code formatting with Back
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./"

      - name: Setup Flake8 Annotations
        uses: rbialon/flake8-annotations@v1.1

      - name: Lint with Flake8
        uses: py-actions/flake8@v2
