name: Linting and Format Jupyter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-format-jupyter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Flake8 for Jupyter Notebooks
        run: |
          pip install --upgrade pip
          pip install flake8-nb

      - name: Run Flake8 for Jupyter Notebooks
        run: |
          flake8-nb notebooks/

      - name: Ensure Clean Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
