name: Docker Build and Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/safety-agent:latest .

      - name: Push to Docker Hub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/safety-agent:latest
